.TH "AsmCtx" 3 "Mon Jun 5 2023" "x86Backend" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AsmCtx
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const \fBProgram\fP * \fBprogram\fP"
.br
.ti -1c
.RI "\fBNameTable\fP * \fBglobal_vars\fP"
.br
.ti -1c
.RI "int \fBnumber_of_global_vars\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for x86Backend from the source code\&.
