.TH "Context" 3 "Mon Jun 5 2023" "x86Backend" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Context
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBReferenceArr\fP \fBcall_refs\fP"
.br
.ti -1c
.RI "\fBReferenceArr\fP \fBjump_refs\fP"
.br
.ti -1c
.RI "\fBBuffer\fP * \fBcode\fP"
.br
.ti -1c
.RI "\fBBuffer\fP * \fBdata\fP"
.br
.ti -1c
.RI "\fBBuffer\fP * \fBstdlib\fP"
.br
.ti -1c
.RI "size_t \fBn_locals\fP"
.br
.ti -1c
.RI "FILE * \fBdump\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for x86Backend from the source code\&.
