.TH "DataBase" 3 "Mon Jun 5 2023" "x86Backend" \" -*- nroff -*-
.ad l
.nh
.SH NAME
DataBase
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <DataBase\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "const char * \fBbuffer\fP"
.br
.ti -1c
.RI "\fBBinaryTree\fP * \fBdata_tree\fP"
.br
.ti -1c
.RI "int \fBstatus\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
\fBTodo\fP
.RS 4
satus that new nodes apeared to decide whenether upload data base or not 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for x86Backend from the source code\&.
