.TH "src/IR/Instructions/Instructions.h" 3 "Mon Jun 5 2023" "x86Backend" \" -*- nroff -*-
.ad l
.nh
.SH NAME
src/IR/Instructions/Instructions.h \- This file contains declaration of \fBInstruction\fP class and its derived classes\&.  

.SH SYNOPSIS
.br
.PP
\fC#include 'Value\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBInstruction\fP"
.br
.RI "Abstract class for instruction, that will be executed\&. "
.ti -1c
.RI "class \fBStore\fP"
.br
.RI "\fBInstruction\fP to allocate space for local variable\&. "
.ti -1c
.RI "class \fBLoad\fP"
.br
.RI "\fBInstruction\fP to load value to local var\&. "
.ti -1c
.RI "class \fBBranch\fP"
.br
.RI "\fBInstruction\fP to pass control flow\&. "
.ti -1c
.RI "class \fBCall\fP"
.br
.RI "\fBInstruction\fP to call another function\&. "
.ti -1c
.RI "struct \fBReturn\fP"
.br
.RI "\fBReturn\fP instruction\&. "
.ti -1c
.RI "struct \fBOperator\fP"
.br
.RI "Math operation instruction\&. "
.in -1c
.SS "Enumerations"

.in +1c
.ti -1c
.RI "enum class \fBInstructionType\fP { \fBStore\fP, \fBLoad\fP, \fBOperator\fP, \fBBranch\fP, \fBCall\fP, \fBReturn\fP }"
.br
.ti -1c
.RI "enum class \fBOperatorType\fP { \fBAdd\fP, \fBSub\fP, \fBMul\fP, \fBDiv\fP, \fBBigger\fP, \fBLess\fP, \fBUnknown\fP }"
.br
.in -1c
.SH "Detailed Description"
.PP 
This file contains declaration of \fBInstruction\fP class and its derived classes\&. 


.SH "Author"
.PP 
Generated automatically by Doxygen for x86Backend from the source code\&.
