.TH "md__home_arsenyfucker__desktop__second_semester_x86_back_end_src__r_e_a_d_m_e" 3 "Mon Jun 5 2023" "x86Backend" \" -*- nroff -*-
.ad l
.nh
.SH NAME
md__home_arsenyfucker__desktop__second_semester_x86_back_end_src__r_e_a_d_m_e \- README 
Legacy - директория со старым кодом, написанным для моего \fCязыка\fP\&.
.PP
IR - директория посвящена IR (intermediate representation) коду
.PP
\fBElf\fP - директория посвящена созданию исполняемых файлов для Линуксаdoxygen 
