.TH "NameTable" 3 "Mon Jun 5 2023" "x86Backend" \" -*- nroff -*-
.ad l
.nh
.SH NAME
NameTable
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBLabel\fP ** \fBlabel_arr\fP"
.br
.ti -1c
.RI "size_t \fBarr_size\fP"
.br
.ti -1c
.RI "size_t \fBnumber_of_labels\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for x86Backend from the source code\&.
