.TH "Storage" 3 "Mon Jun 5 2023" "x86Backend" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Storage
.SH SYNOPSIS
.br
.PP
.PP
Inherits \fBNoCopyable\fP\&.
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBStorage\fP (StorageType type, VariableType var_type, name_t owner_name=NULL)"
.br
.ti -1c
.RI "void \fBset_storage_type\fP (StorageType type)"
.br
.ti -1c
.RI "StorageType \fBget_storage_type\fP () const"
.br
.ti -1c
.RI "void \fBset_var_type\fP (VariableType var_type)"
.br
.ti -1c
.RI "VariableType \fBget_var_type\fP () const"
.br
.ti -1c
.RI "\fBStorageData\fP * \fBset_storage_data\fP ()"
.br
.ti -1c
.RI "void \fBincrease_usage\fP ()"
.br
.ti -1c
.RI "void \fBdecrease_usage\fP ()"
.br
.ti -1c
.RI "size_t \fBget_usage\fP () const"
.br
.ti -1c
.RI "data_t \fBget_data\fP () const"
.br
.ti -1c
.RI "GPRegisterNumber \fBget_reg_num\fP () const"
.br
.ti -1c
.RI "size_t \fBget_stack_offset\fP () const"
.br
.ti -1c
.RI "address_t \fBget_address\fP () const"
.br
.ti -1c
.RI "void \fBset_with_reg\fP (\fBReg\fP *reg)"
.br
.ti -1c
.RI "void \fBprint\fP () const"
.br
.ti -1c
.RI "void \fBmove_to_reg\fP (\fBContext\fP *ctx, \fBReg\fP *dest_reg, const char *comment=NULL)"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for x86Backend from the source code\&.
