.TH "SuperStack" 3 "Mon Jun 5 2023" "x86Backend" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SuperStack
.SH SYNOPSIS
.br
.PP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "CANARY \fBopening_canary\fP"
.br
.ti -1c
.RI "\fBelement_t\fP * \fBheap\fP"
.br
.ti -1c
.RI "size_t \fBcapacity\fP"
.br
.ti -1c
.RI "ssize_t \fBtop\fP"
.br
.ti -1c
.RI "int \fBstatus\fP"
.br
.ti -1c
.RI "SrcLocationInfo \fBinit_inf\fP"
.br
.ti -1c
.RI "int \fBheapHash\fP"
.br
.ti -1c
.RI "int \fBhash\fP"
.br
.ti -1c
.RI "CANARY \fBclosing_canary\fP"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for x86Backend from the source code\&.
