.TH "ValueArr< Value_T >" 3 "Mon Jun 5 2023" "x86Backend" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ValueArr< Value_T >
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "Value_T * \fBadd\fP (Value_T *val)"
.br
.ti -1c
.RI "Value_T * \fBget_value\fP (size_t index)"
.br
.ti -1c
.RI "size_t \fBget_size\fP () const"
.br
.ti -1c
.RI "const Value_T * \fBget_const_value\fP (size_t index) const"
.br
.in -1c

.SH "Author"
.PP 
Generated automatically by Doxygen for x86Backend from the source code\&.
