
front:
	./FrontEnd.out test0.gars test0.awp
 	
front_q:
	./FrontEnd.out test1.gars test0.awp
 
back:
	./OldBackend.out test0.awp soft_cpu_asm.txt
 
 ass:	
	./Ass soft_cpu_asm.txt
 
 exec:
	./SOFT_CPU.out soft_cpu_asm.txt.ars
 
